### ISSUE TITLE
个人建议： C-<return>和<return>这两功能合成一个<return>

### ISSUE THREAD

**Issue by 0000-bigtree** [Qquanwei/emacs-guess-word-game#6]
我想了想，这有几种情况可能不太好判断。但是建议可以这样，^_^：

输入完成，回车，如果错误，显示错误，再判断是否有做过字符输入，有字符输入的话，此时再回车的行为还是检查是否正确，不会显示正确的词，也不会切换下一词。如果没有字符输入，则显示正确的词的拼写。再回车下一词。

输入完成，回车，如果正确。直接下一词。

我用了下，个人感觉，一会儿要 C-\<return\>、一会儿要 \<return\> ，手指有点累。

**Comment by Qquanwei** [comment]
??????????????????????????????????bigtree <notifications@github.com>?2019?4?14? ????9:38???????????????????????????????^_^?
?????????????????????????????????????????????????????????????????????????????????????????????????????
???????????????????
??????????????C-????????????

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Qquanwei** [comment]
上面乱码了。
很不错的建议，将两个按键合成一个是更加符合直觉的操作，对于不熟悉的人一会儿加ctrl一会儿不加会导致误操作。

这两天有时间加一下
